# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download ChromeDriver
      run: |
        mkdir chromedriver
        curl -SL https://chromedriver.storage.googleapis.com/LATEST_RELEASE -o ./chromedriver/LATEST_RELEASE
        CHROMEDRIVER_VERSION=$(cat ./chromedriver/LATEST_RELEASE)
        curl -SL https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -o chromedriver.zip
        unzip chromedriver.zip -d chromedriver
        rm chromedriver.zip
        sudo mv chromedriver/chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'maven'
        java-version: '17'

    - name: Run the Code
      run: mvn clean test